AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda CD
Resources:
 LambdaFunctions:
  Type: AWS::Serverless::Function
  Properties:
   Handler: index-photos.lambda_handler
   Runtime: python3.8
   FunctionName: SamplePython
   CodeUri: ./src #Directory the source file is
   Description: 'Lambda for CD'
   MemorySize: 128
   Timeout: 30
   Role: 'arn:aws:iam::942432719716:role/CodePipelineRole'
   Environment:
    Variables:
        REGION: us-east-1

